export { default as About1 } from './About1';
export { default as About2 } from './About2';
export { default as About3 } from './About3';
export { default as Hero } from './Hero';
export { default as NewTracks } from './NewTracks';
export { default as Pricing } from './Pricing';
export { default as Testimonials } from './Testimonials';
export { default as Header } from './Header';
export { default as Footer } from './Footer';